version: '3.7'

services:
  sfcastapiplatformsecurity_api_php_fpm:
    container_name: sfcastapiplatformsecurity-api-php-fpm
    build: docker/php-fpm
    ports:
      - "8800:9001"
    volumes:
      - .:/var/www/sfcastapiplatformsecurity
    depends_on:
      - sfcastapiplatformsecurity_api_db
    environment:
      PHP_IDE_CONFIG: serverName=sfcastapiplatformsecurity
      XDEBUG_CONFIG: remote_port=9999
      PHP_CS_FIXER_IGNORE_ENV: 1

  sfcastapiplatformsecurity_api_http:
    container_name: sfcastapiplatformsecurity-api-http
    image: nginx:1.19.1
    ports:
      - "8810:80"
    depends_on:
      - sfcastapiplatformsecurity_api_php_fpm
    volumes:
      - .:/var/www/sfcastapiplatformsecurity
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf

  sfcastapiplatformsecurity_api_db:
    container_name: sfcastapiplatformsecurity-api-db
    image: postgres:12
    ports:
      - "8820:5432"
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: sfcastapiplatformsecurity
      POSTGRES_DB: sfcastapiplatformsecurity
      POSTGRES_USER: sfcastapiplatformsecurity
